<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('shipping_countries')->insert([
            ['id'=>1, 'country_name' => 'United States', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>2, 'country_name' => 'United Kingdom', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>3, 'country_name' => 'Canada', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>4, 'country_name' =>	'Australi', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>5, 'country_name' =>	'Germany', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>6, 'country_name' =>	'Afghanistan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>7, 'country_name' =>	'Albania', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>8, 'country_name' =>	'Algeria', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>9, 'country_name' =>	'American Samoa', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>10, 'country_name' => 'Andorra', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>11, 'country_name' => 'Angola', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>12, 'country_name' => 'Anguilla', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>13, 'country_name' => 'Antigua & Barbuda', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>14, 'country_name' => 'Argentina', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>15, 'country_name' => 'Armenia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>16, 'country_name' => 'Aruba', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>17, 'country_name' => 'Austria', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>18, 'country_name' => 'Azerbaijan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>19, 'country_name' => 'Bahamas, The', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>20, 'country_name' => 'Bahrain', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>21, 'country_name' => 'Bangladesh', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>22, 'country_name' => 'Barbados', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>23, 'country_name' => 'Belarus', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>24, 'country_name' => 'Belgium', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>25, 'country_name' => 'Belize', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>26, 'country_name' => 'Benin', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>27, 'country_name' => 'Bermuda', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>28, 'country_name' => 'Bhutan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>29, 'country_name' => 'Bolivia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>30, 'country_name' => 'Bosnia & Herzegovina', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>31, 'country_name' => 'Botswana', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>32, 'country_name' => 'Brazil', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>33, 'country_name' => 'British Virgin Is.', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>34, 'country_name' => 'Brunei', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>35, 'country_name' => 'Bulgaria', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>36, 'country_name' => 'Burkina Faso', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>37, 'country_name' => 'Burma', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>38, 'country_name' => 'Burundi', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>39, 'country_name' => 'Cambodia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>40, 'country_name' => 'Cameroon', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>41, 'country_name' => 'Cape Verde', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>42, 'country_name' => 'Cayman Islands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>43, 'country_name' => 'Central African Rep.', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>44, 'country_name' => 'Chad', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>45, 'country_name' => 'Chile', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>46, 'country_name' => 'China', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>47, 'country_name' => 'Colombia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>48, 'country_name' => 'Comoros', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>49, 'country_name' => 'Congo, Dem. Rep.', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>50, 'country_name' => 'Congo, Repub. of the', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>51, 'country_name' => 'Cook Islands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>52, 'country_name' => 'Costa Rica', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>53, 'country_name' => 'Cote d\'Ivoire', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>54, 'country_name' => 'Croatia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>55, 'country_name' => 'Cyprus', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>56, 'country_name' => 'Czech Republic', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>57, 'country_name' => 'Denmark', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>58, 'country_name' => 'Djibouti', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>59, 'country_name' => 'Dominica', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>60, 'country_name' => 'Dominican Republic', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>61, 'country_name' => 'East Timor', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>62, 'country_name' => 'Ecuador', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>63, 'country_name' => 'Egypt', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>64, 'country_name' => 'El Salvador', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>65, 'country_name' => 'Equatorial Guinea', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>66, 'country_name' => 'Eritrea', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>67, 'country_name' => 'Estonia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>68, 'country_name' => 'Ethiopia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>69, 'country_name' => 'Faroe Islands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>70, 'country_name' => 'Fiji', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>71, 'country_name' => 'Finland', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>72, 'country_name' => 'France', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>73, 'country_name' => 'French Guiana', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>74, 'country_name' => 'French Polynesia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>75, 'country_name' => 'Gabon', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>76, 'country_name' => 'Gambia, The', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>77, 'country_name' => 'Gaza Strip', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>78, 'country_name' => 'Georgia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>79, 'country_name' => 'Ghana', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>80, 'country_name' => 'Gibraltar', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>81, 'country_name' => 'Greece', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>82, 'country_name' => 'Greenland', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>83, 'country_name' => 'Grenada', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>84, 'country_name' => 'Guadeloupe', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>85, 'country_name' => 'Guam', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>86, 'country_name' => 'Guatemala', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>87, 'country_name' => 'Guernsey', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>88, 'country_name' => 'Guinea', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>89, 'country_name' => 'Guinea-Bissau', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>90, 'country_name' => 'Guyana', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>91, 'country_name' => 'Haiti', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>92, 'country_name' => 'Honduras', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>93, 'country_name' => 'Hong Kong', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>94, 'country_name' => 'Hungary', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>95, 'country_name' => 'Iceland', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>96, 'country_name' => 'India', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>97, 'country_name' => 'Indonesia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>98, 'country_name' => 'Iraq', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>99, 'country_name' => 'Ireland', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>100, 'country_name' => 'Isle of Man', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>101, 'country_name' => 'Israel', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>102, 'country_name' => 'Italy', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>103, 'country_name' => 'Jamaica', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>104, 'country_name' => 'Japan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>105, 'country_name' => 'Jersey', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>106, 'country_name' => 'Jordan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>107, 'country_name' => 'Kazakhstan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>108, 'country_name' => 'Kenya', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>109, 'country_name' => 'Kiribati', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>110, 'country_name' => 'Korea, South', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>111, 'country_name' => 'Kuwait', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>112, 'country_name' => 'Kyrgyzstan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>113, 'country_name' => 'Laos', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>114, 'country_name' => 'Latvia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>115, 'country_name' => 'Lebanon', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>116, 'country_name' => 'Lesotho', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>117, 'country_name' => 'Liberia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>118, 'country_name' => 'Libya', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>119, 'country_name' => 'Liechtenstein', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>120, 'country_name' => 'Lithuania', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>121, 'country_name' => 'Luxembourg', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>122, 'country_name' => 'Macau', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>123, 'country_name' => 'Macedonia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>124, 'country_name' => 'Madagascar', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>125, 'country_name' => 'Malawi', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>126, 'country_name' => 'Malaysia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>127, 'country_name' => 'Maldives', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>128, 'country_name' => 'Mali', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>129, 'country_name' => 'Malta', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>130, 'country_name' => 'Marshall Islands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>131, 'country_name' => 'Martinique', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>132, 'country_name' => 'Mauritania', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>133, 'country_name' => 'Mauritius', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>134, 'country_name' => 'Mayotte', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>135, 'country_name' => 'Mexico', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>136, 'country_name' => 'Micronesia, Fed. St.', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>137, 'country_name' => 'Moldova', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>138, 'country_name' => 'Monaco', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>139, 'country_name' => 'Mongolia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>140, 'country_name' => 'Montserrat', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>141, 'country_name' => 'Morocco', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>142, 'country_name' => 'Mozambique', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>143, 'country_name' => 'Namibia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>144, 'country_name' => 'Nauru', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>145, 'country_name' => 'Nepal', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>146, 'country_name' => 'Netherlands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>147, 'country_name' => 'Netherlands Antilles', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>148, 'country_name' => 'New Caledonia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>149, 'country_name' => 'New Zealand', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>150, 'country_name' => 'Nicaragua', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>151, 'country_name' => 'Niger', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>152, 'country_name' => 'Nigeria', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>153, 'country_name' => 'N. Mariana Islands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>154, 'country_name' => 'Norway', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>155, 'country_name' => 'Oman', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>156, 'country_name' => 'Pakistan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>157, 'country_name' => 'Palau', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>158, 'country_name' => 'Panama', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>159, 'country_name' => 'Papua New Guinea', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>160, 'country_name' => 'Paraguay', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>161, 'country_name' => 'Peru', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>162, 'country_name' => 'Philippines', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>163, 'country_name' => 'Poland', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>164, 'country_name' => 'Portugal', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>165, 'country_name' => 'Puerto Rico', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>166, 'country_name' => 'Qatar', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>167, 'country_name' => 'Reunion', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>168, 'country_name' => 'Romania', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>169, 'country_name' => 'Russia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>170, 'country_name' => 'Rwanda', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>171, 'country_name' => 'Saint Helena', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>172, 'country_name' => 'Saint Kitts & Nevis', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>173, 'country_name' => 'Saint Lucia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>174, 'country_name' => 'St Pierre & Miquelon', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>175, 'country_name' => 'Saint Vincent and the Grenadines', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>176, 'country_name' => 'Samoa', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>177, 'country_name' => 'San Marino', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>178, 'country_name' => 'Sao Tome & Principe', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>179, 'country_name' => 'Saudi Arabia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>180, 'country_name' => 'Senegal', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>181, 'country_name' => 'Serbia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>182, 'country_name' => 'Seychelles', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>183, 'country_name' => 'Sierra Leone', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>184, 'country_name' => 'Singapore', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>185, 'country_name' => 'Slovakia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>186, 'country_name' => 'Slovenia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>187, 'country_name' => 'Solomon Islands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>188, 'country_name' => 'Somalia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>189, 'country_name' => 'South Africa', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>190, 'country_name' => 'Spain', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>191, 'country_name' => 'Sri Lanka', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>192, 'country_name' => 'Sudan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>193, 'country_name' => 'Suriname', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>194, 'country_name' => 'Swaziland', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>195, 'country_name' => 'Sweden', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>196, 'country_name' => 'Switzerland', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>197, 'country_name' => 'Taiwan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>198, 'country_name' => 'Tajikistan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>199, 'country_name' => 'Tanzania', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>200, 'country_name' => 'Thailand', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>201, 'country_name' => 'Togo', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>202, 'country_name' => 'Tonga', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>203, 'country_name' => 'Trinidad & Tobago', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>204, 'country_name' => 'Tunisia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>205, 'country_name' => 'Turkey', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>206, 'country_name' => 'Turkmenistan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>207, 'country_name' => 'Turks & Caicos Is', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>208, 'country_name' => 'Tuvalu', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>209, 'country_name' => 'Uganda', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>210, 'country_name' => 'Ukraine', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>211, 'country_name' => 'United Arab Emirates', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>212, 'country_name' => 'Uruguay', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>213, 'country_name' => 'Uzbekistan', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>214, 'country_name' => 'Vanuatu', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>215, 'country_name' => 'Venezuela', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>216, 'country_name' => 'Vietnam', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>217, 'country_name' => 'Virgin Islands', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>218, 'country_name' => 'Wallis and Futuna', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>219, 'country_name' => 'West Bank', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>220, 'country_name' => 'Western Sahara', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>221, 'country_name' => 'Yemen', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>222, 'country_name' => 'Zambia', 'created_at' => NOW(), 'updated_at' => NOW()],
            ['id'=>223, 'country_name' => 'Zimbabwe', 'created_at' => NOW(), 'updated_at' => NOW()]
        ]);
    }
}
